MVCuus/Models/Person.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCuus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.UserInRoles = new HashSet<UserInRole>();
            this.Travels = new HashSet<Travel>();
        }
      
        public int Id { get; set; } 
        [DisplayName("Isikukood")]
        public string PersonID { get; set; }
        [DisplayName("Eesnimi")]
        public string FirstName { get; set; }
        [DisplayName("Perekonnanimi")]
        public string LastName { get; set; }
        [DisplayName("Registreeritud")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime StartDate { get; set; }
        [DisplayName("Staatus")]
        public int PersonState { get; set; }
        [DisplayName("Osakonna Id")]
        public int DepartmentID { get; set; }
        [DisplayName("Foto")]
        public Nullable<int> Picture { get; set; }
        [DisplayName("E-mail")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel> Travels { get; set; }
        public virtual File File { get; set; }
    }
}

MVCuus/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCuus.Models;



namespace MVCuus.Models
{
    partial class Person
    {

        public static Dictionary<int, string> States = new Dictionary<int, string>
        {
            {0, "ootel" },
            {1, "aktiivne" },
            {2, "puhkusel" },
            {3, "pensionil" },
            {4, "lahkunud" }
        };
        [DisplayName("Staatus")]
        public string State => States[this.PersonState];

        static SiimJaSEntities db = new SiimJaSEntities();

        public string FullName => FirstName + " " + LastName;

        public string FullNameIsikukoodiga => FirstName + " " + LastName + " " + PersonID;

        public static Person GetByEmail(string email)
            => db.People.Where(x => x.Email == email).SingleOrDefault();

        public bool IsInRole(string rolename)
            => this.UserInRoles
                .Select(x => x.Role.RoleName.ToLower()).ToList()
                .Intersect(rolename.Split(',').Select(y => y.Trim().ToLower()))
                .Count() > 0;

    }
    
}


namespace MVCuus.Controllers
{

    public class PeopleController : Controller
    {
        public SiimJaSEntities db = new SiimJaSEntities();



        // GET: People
        // Muutsin meetodit, et luua pagination funktsionaalsuse loomiseks vajalik
        // Lisasin ka sorteerimise võimaluse

        public ActionResult Index(string searchBy, string search, int page = 0, int size = 20, string sort = "PersonID", string direction = "ascending")
        {
            ViewBag.Page = page;
            ViewBag.Size = size;
            ViewBag.Pages = db.People.Count() / size;
            ViewBag.Sort = sort;
            ViewBag.Direction = direction;

            var sorted =
                 (direction == "descending" && sort == "FirstName") ? db.People.OrderByDescending(x => x.FirstName)
                : (sort == "FirstName") ? db.People.OrderBy(x => x.FirstName)
                : (direction == "descending" && sort == "LastName") ? db.People.OrderByDescending(x => x.LastName)
                : (sort == "LastName") ? db.People.OrderBy(x => x.LastName)
                : (direction == "descending") ? db.People.OrderByDescending(x => x.PersonID)
                : db.People.OrderBy(x => x.PersonID);

            if (Request.IsAuthenticated)
            {
                if (searchBy == "LastName")
                    return View(db.People.Where(x => x.LastName == search || search == null).ToList());
                if (searchBy == "FirstName")
                    return View(db.People.Where(x => x.FirstName.StartsWith(search) || search == null).ToList());
                else
                    return View(sorted.Skip(page * size).Take(size).ToList());

                //return View(sorted.Skip(page * size).Take(size).ToList()
                //    if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Admin") ?? false))
                //        return View(sorted.Skip(page * size).Take(size).ToList().Union(db.People.Where(x => x.LastName == search || search == null).ToList()));


            }
            return RedirectToAction("Login", "Account");

        }  
       

    public ActionResult AddRole(int? id, int? roleid)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            if (roleid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(roleid);
            if (role == null)
            {
                return HttpNotFound();
            }

            try
            {
                db.UserInRoles.Add(new UserInRole { PersonId = id.Value, RoleId = roleid.Value });
                db.SaveChanges();
            }
            catch { }

            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult RemoveRole(int? id, int? roleid)
        {
            Role r = db.Roles.Find(roleid ?? 0);
            Person p = db.People.Find(id ?? 0);
            if (p == null) return RedirectToAction("Index");
            if (r != null) 
            try
            {
                var uir = db.UserInRoles.Where(x => x.RoleId == roleid.Value && x.PersonId == id.Value).SingleOrDefault();
                if (uir != null) db.UserInRoles.Remove(uir);
                db.SaveChanges();
            }
            catch { }
            return RedirectToAction("Details", new { id = id.Value });
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Person person = db.People.Find(id);
                if (person == null)
                {
                    return HttpNotFound();
                }
                ViewBag.NewRoles = db.Roles.Where(x => !x.UserInRoles.Select(y => y.PersonId).ToList().Contains(id.Value));

                return View(person);
            }
            else return RedirectToAction("Login", "Account");
        }

        // GET: People/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "DepartmentName");
                ViewBag.PersonState = new SelectList(Person.States, "Key", "Value");
                ViewBag.RoleId = new SelectList(db.Roles, "Id", "RoleName");

                return View();
            }
            else return RedirectToAction("Login", "Account");
        }

        //ViewBag.PersonID = new SelectList(db.People, "Id", "FullName");
        //    return View();

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // Lisatud HttpPostedFileBase file, mis on vajalik, et saaks pilti yles laadida
        public ActionResult Create([Bind(Include = "Id,PersonID,FirstName,LastName,StartDate,PersonState,DepartmentID,Picture,Email")] Person person, int RoleId, HttpPostedFileBase file) //siia lisasin int role id, et see salvestuks töötaja lisamise juures
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid) // && person.DepartmentID != 0)
                {
                    //See lõik on vajalik, et töötajate lisamis lehel saaks töötajale lisada ka rolli
                    Role r = db.Roles.Find(RoleId);
                    if (r != null) person.UserInRoles.Add(new UserInRole { Role = r });
                    db.People.Add(person);

                    db.SaveChanges();

                    return RedirectToAction("Index");

                }//Selle rea kopeerisin, et dropdownis ei saaks valida tühja lehte
                ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "DepartmentName");
                ViewBag.PersonState = new SelectList(Person.States, "Key", "Value");
                ViewBag.RoleId = new SelectList(db.Roles, "Id", "RoleName");
                return View(person);
            }
            else return RedirectToAction("Login", "Account");
        }

        // Kogu see ActionResult on lisatud pildi lisamiseks
        // POST: People/AddPicture/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPicture([Bind(Include = "Id")]Person person0, HttpPostedFile pilt)
        {
            int id = person0.Id;
            Person person = db.People.Find(id);
            if (person == null) return RedirectToAction("Index");
            if (pilt == null || pilt.ContentLength == 0) return RedirectToAction("Details", new { id = id });
            File newFile = new File();
            using (System.IO.BinaryReader br = new System.IO.BinaryReader(pilt.InputStream))
            {
                byte[] buff = br.ReadBytes(pilt.ContentLength);
                newFile.Content = buff;
            }
            db.SaveChanges();
            person.Picture = newFile.Id;
            db.SaveChanges();


            return RedirectToAction("Details", new { id = id });
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Person person = db.People.Find(id);
                if (person == null)
                {
                    return HttpNotFound();
                }
                // Lisada hiljem
                //ViewBag.PersonState = new SelectList(Person.States, "Key", "Value", person.PersonState);

                // Saab valida departmenti inimesele
                // Id on Key ja DepartmentName on value
                ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "DepartmentName", person.Department);
                ViewBag.PersonState = new SelectList(Person.States, "Key", "Value");
                ViewBag.RoleId = new SelectList(db.Roles, "Id", "RoleName");
                ViewBag.NewRoles = db.Roles.Where(x => !x.UserInRoles.Select(y => y.PersonId).ToList().Contains(id.Value));
                return View(person);
            }

MVCuus/Views/People/Delete.cshtml
@model MVCuus.Models.Person

@{
    ViewBag.Title = "Delete";
}
<link href="~/StyleSheet1.css" rel="stylesheet" />
<h2>@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h2>

<h3>Kas soovid kustutada selle töötaja?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    <p>
    <p>
        @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </div>

            <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class = "btn btn-primary" })</b>
            }
        </div>

MVCuus/Views/People/Edit.cshtml
@model MVCuus.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Muuda</h2>

@* Selle lisasin, et saaks pilti yles laadida *@
@using (Html.BeginForm("Edit", "People", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.PersonID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PersonID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Osakond", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentId", null, "-- vali osakond --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>


    @*<div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @* Selle rea kommenteerisin välja, kuna muutmise all ei ole vaja lisada alustamise kuupäeva *@

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PersonState, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.PersonState, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.DropDownListFor(model => model.PersonState, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PersonState, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserInRoles, "Roll", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("RoleId", null, "-- vali roll --", htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.UserInRoles, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.UserInRoles, "", new { @class = "text-danger" })
        </div>
    </div>

    @*People lehel olevate inimeste Details lehele laheb kirje selle kohta, mis rollides see inimene on*@
    <h2>@Model.FullName omab järgnevaid rolle</h2>
    <ol>
        @foreach (var x in Model.UserInRoles)
        {
            <li> @Html.ActionLink("- " + @x.Role.RoleName, "RemoveRole", new { id = Model.Id, roleid = x.Role.Id }) </li>
        }
    </ol>

    <h2>@Model.FullName ei oma neid rolle</h2>
    <ol>
        @foreach (MVCuus.Models.Role r in ViewBag.NewRoles)
        {
            <li>@Html.ActionLink("+ " + r.RoleName, "AddRole", new { id = Model.Id, roleid = r.Id }) </li>
        }
    </ol>


    @*<div class="form-group">
        @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
        </div>
    </div>*@
    @* Naidatakse pilti korgusega 120 px *@
    @*@if (Model.Picture != null)
    {
        <img src="@Url.Action("Get", "Files", new { id = Model.Picture})" height=120 />
    }*@
    @* Kui on pilt, siis ytleb, et vali uus pilt. Kui pilti pole, siis "uus" ei oelda *@
    @*<br /><label for=" file">Vali @(Model.Picture == null ? "" : "uus" ) pilt @Model.FullName jaoks:</label>
    <input type="file" name="file" id="file" />*@



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class="btn btn-primary"})</b>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCuus/Views/People/Index.cshtml
@model IEnumerable<MVCuus.Models.Person>

@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-color: lightyellow
    }
</style>
@*<link href="~/StyleSheet1.css" rel="stylesheet" />*@
<h2>Töötajad</h2>

<p>
    @if (Request.IsAuthenticated)
        {
            MVCuus.Models.SiimJaSEntities db = new MVCuus.Models.SiimJaSEntities();
            var people = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            if (people != null)
            {
                if (people.UserInRoles.Select(x => x.Role.RoleName).Contains("Admin"))
                {
    @Html.ActionLink("Loo uus", "Create", null, new { @class = "btn btn-primary" })
            }
           }
        }

<p>
    @using (Html.BeginForm("Index", "People", FormMethod.Get))
    {
        <b> Otsi töötajat:</b>
        // need koodid on selleks, kui tahta ka perekonna nime järgi otsingut. Koodil on mingi pisiviga ning hästi ei tööta. Kui  jääb aega, siis teen korda. Praegu aega ei raiska
        @Html.RadioButton("searchBy", "FirstName", true) <text> Eesnimi </text>
        @Html.RadioButton("searchBy", "LastName") <text>Perekonnanimi</text>
        @*@Html.RadioButton("Otsi", "DepartmentId") <text>Osakond</text> <br />*@
        @Html.TextBox("search") <input type="submit" value="Otsi" />
    }

</p>
@*@using (Html.BeginForm())
    {
    <p>
        Title: @Html.TextBox("Otsi töötaja") <br />
        <input type="submit" value="Filter" />
    </p>*@
@*}*@


@*Pagination funktsionaalsus*@
<p>

    @if (ViewBag.Page > 0)
    {
        <b>
            @Html.ActionLink(" << ", "Index", new { page = 0, sort = ViewBag.Sort, direction = ViewBag.Direction }) |
            @Html.ActionLink(" < ", "Index", new { page = Math.Max(ViewBag.Page - 1, 0), sort = ViewBag.Sort, direction = ViewBag.Direction }) |
        </b>
    }
    @if (ViewBag.Page < ViewBag.Pages)
    {
        <b>
            @Html.ActionLink(" > ", "Index", new { page = Math.Min(ViewBag.Page + 1, ViewBag.Pages), sort = ViewBag.Sort, direction = ViewBag.Direction }) |
            @Html.ActionLink(" >> ", "Index", new { page = ViewBag.Pages, sort = ViewBag.Sort, direction = ViewBag.Direction }) |
        </b>
    }
</p>



@* Lisasin sorteerimisvõimaluse *@
<table class="table">
    <tr style="background-color: darkgrey; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: black">
        <th>
            @*@Html.DisplayNameFor(model => model.PersonID)*@
            @Html.ActionLink(Html.DisplayNameFor(model => model.PersonID).ToHtmlString(), "Index", new { direction = ((ViewBag.Sort == "PersonID" && ViewBag.Direction == "ascending") ? "descending" : "ascending"), sort = "PersonID" })
            @* See ülemine rida on Hennu tehtud, mida tuleks kasutada juhul, kui leht oleks multikeelne. Meie töö puhul sobivad ka alumised lahendused *@
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.FirstName)*@
            @Html.ActionLink("Eesnimi", "Index", new { direction = ((ViewBag.Sort == "FirstName" && ViewBag.Direction == "ascending") ? "descending" : "ascending"), sort = "FirstName" })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.LastName)*@
            @Html.ActionLink("Perenimi", "Index", new { direction = ((ViewBag.Sort == "LastName" && ViewBag.Direction == "ascending") ? "descending" : "ascending"), sort = "LastName" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentID)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.UserInRoles)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>

    @if (Model.Count() == 0)
    {

    <tr>
     
            <td colspan="4"> Sellise nimega inimest ei leitud!</td>
          
    </tr>

    }
    else
    {

        foreach (var item in Model)
        {
            <tr style="background-color: lightgoldenrodyellow">
                <td>
                    @Html.DisplayFor(modelItem => item.PersonID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartmentID)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.UserInRoles)
                    </td>*@

                @*<td>
                    @Html.DisplayFor(modelItem => item.Picture)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @if (Request.IsAuthenticated)
                    {
                        MVCuus.Models.SiimJaSEntities db = new MVCuus.Models.SiimJaSEntities();
                        var people = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                        if (people != null)
                        {
                            if (people.UserInRoles.Select(x => x.Role.RoleName).Contains("Admin"))
                            {
                                @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) 
                            }
                        }
                    }
                    |
                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |

                    @if (Request.IsAuthenticated)
                    {
                        MVCuus.Models.SiimJaSEntities db = new MVCuus.Models.SiimJaSEntities();
                        var people = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                        if (people != null)
                        {
                            if (people.UserInRoles.Select(x => x.Role.RoleName).Contains("Admin"))
                            {
                                @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                            }
                        }
                    }

                </td>
            </tr>
        }
    }

</table>
      
         
                   