MVCuus/Controllers/TravelsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using MVCuus.Models;


namespace MVCuus.Controllers
{
    public class TravelsController : Controller
    {
        private SiimJaSEntities db = new SiimJaSEntities();
    

       
        public ActionResult Index(string alates, string kuni, [Bind(Include = "Amount")] Travel travel)
        {
            // Valib poole aasta taguse aja, sest vastavalt nõuetele peab vaates nägema aruandeid alates poole aasta tagusest ajast. 
            TimeSpan poolAastatTagasi = new TimeSpan(4340, 0, 0); // tunnid, minutid, sekundid 4340
            DateTime tanaPoolAastatTagasi = DateTime.Today - poolAastatTagasi;

            DateTime dateAlates = DateTime.TryParse(alates, out DateTime da) ? da : tanaPoolAastatTagasi;
            DateTime dateKuni = DateTime.TryParse(kuni, out DateTime dk) ? dk : DateTime.Today;  //new DateTime(2020, 12, 31);

            ViewBag.alates = dateAlates;
            ViewBag.kuni = dateKuni;


            //var travels = db.Travels.Include(e => e.Person).ToList();
            var travels = db.Travels.Include(e => e.Person).ToList()
                    .Where(x => x.EndDate >= dateAlates)
                    .Where(x => x.EndDate <= dateKuni)
                    .ToList();

            if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Admin") ?? false))
                //Siin näidatakse kõiki aruandeid, mis ei ole staatusega 0 ehk mis ei ole pooleliolevad pluss
                //kõik raamatupidaja enda aruanded
                return View(travels.Where(x=>x.ReportState!=0).Union(db.Travels.Where(x => x.PersonId == db.People.Where(y => y.Email == User.Identity.Name).FirstOrDefault().Id)));
            else if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Ettevõtte juht") ?? false))
                //Siin näidatakse kõiki juhi all olevate töötajate aruandeid, mis ei ole staatusega 0 ehk mis ei ole pooleliolevad pluss
                //need juhi aruandeid, mis ei ole esitatud staatusega kuna nendega pole tal midagi teha, need on saadetud kinnitamisele raamatupidajale omakorda
                return View(travels.Where(x=>x.PersonId != db.People.Where(y => y.Email == User.Identity.Name).Single().Id).Where(x=>x.ReportState>0).
                Union(db.Travels.Where(x => x.PersonId == db.People.Where(y => y.Email == User.Identity.Name).FirstOrDefault().Id).Where(x => x.ReportState != 1).Where(x => x.ReportState != -1)));
            else if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Osakonna juht") ?? false))
                //Siin näidatakse alluvate aruandeid, mis on saadetud kinnitamisele ehk esitatud staatusega ja kinnitatud staatusega aruandeid pluss
                //osakonnajuhataja need aruanded, mis ei ole esitatud, kuna nendega pole tal midagi teha, need on saadetud ülevaatamisele oma otsesele juhile ja 
                //seejärel kinnitamisele raamatupidajale omakorda 
                return View(travels.Join(db.People.Where(y => y.DepartmentID == db.People.
                Where(z => z.Email == User.Identity.Name).FirstOrDefault().DepartmentID), x=>x.PersonId, z=>z.Id, (x,z)=>x).
                Where(x=>x.PersonId != db.People.Where(y => y.Email == User.Identity.Name).Single().Id).Where(x=>x.ReportState>0).
                Union(db.Travels.Where(x => x.PersonId == db.People.Where(y => y.Email == User.Identity.Name).FirstOrDefault().Id).Where(x=>x.ReportState!=1).Where(x => x.ReportState != -1)));
            else if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Tavakasutaja") ?? false))
                return View(travels.Where(x => x.PersonId == db.People.Where(y => y.Email == User.Identity.Name).Single().Id).Where(x=>x.ReportState!=-1).Where(x => x.ReportState != 1));
            else
                return RedirectToAction("Login", "Account");
        }

        private IEnumerable<Person> PeopleFilter()
        {
            //if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Osakonna juht") ?? false))
            //    return db.People.Where(y => y.DepartmentID == db.People.
            //    Where(z => z.Email == User.Identity.Name).FirstOrDefault().DepartmentID);
            //else if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Tavakasutaja") ?? false))
            //    return db.People.Where(y => y.Email == User.Identity.Name);
            //else return db.People;

            return db.People.Where(y => y.Email == User.Identity.Name);
        } 
        

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            if (Request.IsAuthenticated && (Person.GetByEmail(User.Identity.Name)?.IsInRole("Admin") ?? false))

                return View();
            else return RedirectToAction("Index");
        }




        // GET: Travels/Details/5
        public ActionResult Details(int? id, string back = "")
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Travel travel = db.Travels.Find(id);
                ViewBag.PersonId = new SelectList(db.People, "Id", "FullName");
                ViewBag.sps = db.Spendings.Where(x => x.TravelId == travel.Id);
                if (travel == null)
                {
                    return HttpNotFound();
                }

                Nullable<decimal> Summa = db.Spendings.Where(x => x.TravelId == travel.Id).Sum(x => x.Amount);
                ViewBag.Sum = Summa == null ? 0 : Summa;
                ViewBag.Back = back;
                return View(travel);
            }
            else return RedirectToAction("Login", "Account");
        }
        
        

        // GET: Travels/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.PersonId = new SelectList(PeopleFilter(), "Id", "FullName");
                ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");

                var travels = db.Travels.Include(t => t.Person);
                //Custom c = new Custom();

                return View();
            }
            else return RedirectToAction("Login", "Account");
        }

        // POST: Travels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TravelName,StartDate,EndDate,Description,ReportState, RepStatus,PersonId,TypeId,Amount,Document,Feedback")] Travel travel)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Travels.Add(travel);
                    db.SaveChanges();

                    return RedirectToAction("Edit", new { id = travel.Id });
                }

                return View(travel);
            }
            else return RedirectToAction("Login", "Account");
        }

        // GET: Travels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Travel travel = db.Travels.Find(id);
                /*travel.Feedback = "niiteha"*/
                ;
                ViewBag.Feedback = travel.Feedback;
                //0 - Pooleli olev
                //1 - Esitatud
                //2 - Kinnitatud
                //-1 - Raamatupidaja käes
                if (travel.ReportState == 1)
                {
                    ViewBag.repState = "disabled";
                }
                if (travel.ReportState == 0 || travel.ReportState == 2)
                {
                    ViewBag.repConfirm = "disabled";
                }
                if (travel.ReportState == 2)
                {
                    ViewBag.repState = "disabled";
                }
                if (travel.ReportState == -1)
                {
                    ViewBag.repState = "disabled";
                }
                ViewBag.PersonId = new SelectList(db.People, "Id", "FullName");
                ViewBag.sps = db.Spendings.Where(x => x.TravelId == travel.Id);
                if (travel == null)
                {
                    return HttpNotFound();
                }

                Nullable<decimal> Summa = db.Spendings.Where(x => x.TravelId == travel.Id).Sum(x => x.Amount);
                ViewBag.Sum = Summa == null ? 0 : Summa;

                return View(travel);
            }
            else return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "Edit")]
        public ActionResult Edit([Bind(Include = "Id,TravelName,StartDate,EndDate,Description,ReportState,RepStatus,PersonId,Feedback")] Travel travel)
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.PersonId = new SelectList(db.People, "Id", "FullName");
                ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");

MVCuus/Views/Travels/AddSpending.cshtml
@model MVCuus.Models.Travel

@{
    ViewBag.Title = "Täienda";
}
<style>
    body {
        background-color: lightyellow
    }
</style>
@*<link href="~/StyleSheet1.css" rel="stylesheet" />*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <table class="table">

            <tr>
                <td>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <h4><b>ÜLDANDMED:</b></h4>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.PersonId, null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TravelName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TravelName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TravelName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, 6, 50, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <table>
                        <tr>
                            <td>
                                <h5><b>@Html.DisplayNameFor(model => model.ReportState)&nbsp</b></h5>
                            </td>
                            <td>
                                <h4>&nbsp <u>@Html.DisplayFor(model => model.RepStatus)</u></h4>
                            </td>
                        </tr>
                    </table>
                    <hr />

                    <div class="form-group">

                        <table>
                            <tr>
                                <td>
                                    <div class="col-sm-offset-0 col-sm-1">
                                        <input type="submit" value="Salvesta ja välju" name="action:Edit" class="btn btn-primary" disabled="@ViewBag.repState" />
                                    </div>
                                </td>
                                <td>
                                    <div class="col-sm-offset-0 col-sm-1">
                                        <input type="submit" value="Esita kinnitamiseks" name="action:ForConfirm" class="btn btn-primary" disabled="@ViewBag.repState" />
                                    </div>
                                </td>
                                <td>
                                    <div class="col-sm-offset-0 col-sm-1">
                                        <input type="submit" value="Saada RMP-le" name="action:ForBooking" class="btn btn-primary" disabled="@ViewBag.repConfirm" />
                                    </div>
                                </td>
                                <td>
                                    <div class="col-sm-offset-0 col-sm-1">
                                        <input type="submit" value="Kinnita" name="action:Confirm" class="btn btn-primary" disabled="@ViewBag.repConfirm" />
                                    </div>
                                </td>
                                <td>
                                    <div class="col-sm-offset-0 col-sm-1">
                                        <input type="submit" value="Lükka tagasi" name="action:NotConfirm" class="btn btn-primary" disabled="@ViewBag.repConfirm" />
                                    </div>
                                </td>

                            </tr>
                        </table>
                        <p></p>
                        @*<table>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Feedback, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            &nbsp   @Html.TextAreaFor(model => model.Feedback, 2, 50, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Feedback, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>*@
                    </div>
                </td>
                <td>
                    <h4><b>REISIKULU ANDMED:</b></h4>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TypeId, "Kulu", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TypeId", null, "--Vali kulu liik--", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Document, "Fail", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Document, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lisa" name="action:AddSpending" class="btn btn-primary" disabled="@ViewBag.repState" />
                            <p></p>
                        </div>
                    </div>


                    <table border="1" class="table">

                        <tr>
                            <th>
                                <b>Kulu liik</b>
                            </th>
                            <th>
                                <b>Summa</b>
                            </th>
                            <th>
                                <b>Dokument</b>
                            </th>
                            <th>
                                <b>Halda kulu</b>
                            </th>
                        </tr>
                        @foreach (var x in ViewBag.sps)
                        {

                            <tr>
                                <td>
                                    @x.SpeType
                                </td>
                                <td>
                                    @x.Amount
                                </td>
                                <td>
                                    @*@x.File*@
                                </td>

                                <td>
                                    @Html.ActionLink("Muuda", "Edit", "Spendings", new { id = x.Id, back = "person" }, null) |
                                    @Html.ActionLink("Detailid", "Details", "Spendings", new { id = x.Id, back = "person" }, null) |
                                    @Html.ActionLink("Kustuta", "Delete", "Spendings", new { id = x.Id, back = "person" }, null)
                                    @*@using (Html.BeginForm("DeleteSpending", "Travels", new { id = x.Id }, FormMethod.Post, null))
        {
            <input type="submit" value="Delete" />
        }*@
                                </td>
                            </tr>

                        }
                    </table>
                    <table>
                        <tr>
                            <td>
                                <h4><b>Reisikulu kokku:&nbsp</b></h4>
                            </td>
                            <td>
                                <h4>@ViewBag.Sum €</h4>
                            </td>
                        </tr>
                    </table>

                </td>



            </tr>

        </table>
    </div>
}

<div>
    @*@if (ViewBag.Back == "person")
        {
            <õ>
                @Html.ActionLink("Back to person", "Edit", "People", new { id = Model.PersonId }, null)
            </õ>
        }
        else
        {
        <õ>*@
    <b>@Html.ActionLink("Tagasi nimekirja", "Index", null, new { @class = "btn btn-primary" })</b>
    @*</õ>
        }*@

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCuus/Views/Travels/Index.cshtml
@model IEnumerable<MVCuus.Models.Travel>

@{
    ViewBag.Title = "Index";
}
<style>
    body {background-color: lightyellow}
</style>
@*<link href="~/StyleSheet1.css" rel="stylesheet" />*@
<h2>Reisid</h2>

<p>
    <b>@Html.ActionLink("Loo uus", "Create", null, new { @class = "btn btn-primary" })</b>
</p>


@using (Html.BeginForm("Index", "Travels", FormMethod.Post))
{
    <p>
        <b>Viimase poole aasta reisiaruanded: </b>

            <input type="text" id="alates" name="alates" class="datepicker form-control" style="text-align:center" value="@ViewBag.alates.ToShortDateString()" onchange="this.form.submit()" />
            <input type="text" id="kuni" name="kuni" class="datepicker form-control" style="text-align:center" value="@ViewBag.kuni.ToShortDateString()" onchange="this.form.submit()" /><br>
        </p>

    @*@Html.Editor("alates", new { type = "date", @class = "datepicker form-control" })
        @Html.Editor("kuni", new { type = "date", @class = "datepicker form-control" })*@

    @*<input type="submit" value="otsi" />*@


}







<table class="table">

    <tr style="background-color: darkgrey; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: black; text-align:center">
        <th style="width:150px">
            @Html.DisplayNameFor(model => model.TravelName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th style="text-align:center">
            @Html.DisplayNameFor(model => model.ReportState)
        </th>
        <th style="text-align:center">
            Töötaja
        </th>
        <th style="text-align:center">
            Kulud kokku
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        var reportstatecheck = item.ReportState;

        if (reportstatecheck == 0)
        {
            @*<tr @(item.ReportState == 0 ? "style=backround-color: pink" : "")>*@
            <tr style="background-color:#ffffff">
                <td style="width:150px">
                    @Html.DisplayFor(modelItem => item.TravelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="width:50px">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.RepStatus)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Person.FullName)
                </td>
                <td style="text-align:center">
                    @*@Html.DisplayFor(modelItem => item.Spendings.Sum(x=>x.Amount)))*@
                    @item.Spendings.Sum(x => x.Amount)
                </td>
                <td>
                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        else if (reportstatecheck == 1)
        {
            <tr style="background-color:#ffff99">
            
                <td style="width:150px">
                    @Html.DisplayFor(modelItem => item.TravelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="width:50px">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.RepStatus)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Person.FullName)
                </td>
                <td style="text-align:center">
                    @item.Spendings.Sum(x => x.Amount)
                </td>
                <td>
                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        else if (reportstatecheck == 2)
        {
            <tr style="background-color:#bdf5bd">

                <td style="width:150px">
                    @Html.DisplayFor(modelItem => item.TravelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="width:50px">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.RepStatus)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Person.FullName)
                </td>
                <td style="text-align:center">
                    @item.Spendings.Sum(x => x.Amount)
                </td>
                <td>
                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        else 
        {
            <tr style="background-color:#ffe6e6">

                <td style="width:150px">
                    @Html.DisplayFor(modelItem => item.TravelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="width:50px">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.RepStatus)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Person.FullName)
                </td>
                <td style="text-align:center">
                    @item.Spendings.Sum(x => x.Amount)
                </td>
                <td>
                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }

</table>