MVCuus/Models/Department.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCuus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        [DisplayName("Osakond")]
        public string DepartmentName { get; set; }
        public Nullable<int> Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        public virtual File File { get; set; }
    }
}

MVCuus/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCuus.Models;
using F = System.IO;

namespace MVCuus.Controllers
{
    public class DepartmentsController : Controller
    {
        private SiimJaSEntities db = new SiimJaSEntities();

        //public static Dictionary<int, string> DepartmentName = new Dictionary<int, string>
        //{
        //    {1, "Admin" },
        //    {15, "Tootmisosakond" },
        //    {16, "Müügiosakond" },
        //    {21, "It osakond" },

        //};
        //[DisplayName("Osakond")]
        //public string DepartmentName => DepartmentName[this.DepartmentName];


        // GET: Departments

        public ActionResult Index()
         
        {

            var departments = db.Departments.Include(d => d.File);
            return View(departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            ViewBag.Picture = new SelectList(db.Files, "Id", "Filename");
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DepartmentName,Picture")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.Picture = new SelectList(db.Files, "Id", "Filename", department.Picture);
            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit (int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }

            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DepartmentName")] Department department, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.Entry(department).Property(x => x.Picture).IsModified = false;
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    using (F.BinaryReader br = new F.BinaryReader(file.InputStream))
                    {
                        if (department.Picture != null)
                        {
                            department.Picture = null;
                            db.SaveChanges();
                        }
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        File uusFile = new File
                        {
                            Content = buff,
                            ContentType = file.ContentType,
                            Filename = file.FileName.Split('\\').Last()
                        };
                        db.Files.Add(uusFile);
                        db.SaveChanges();
                        department.Picture = uusFile.Id;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }



            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

MVCuus/Views/Departments/Create.cshtml
@model MVCuus.Models.Department

@{
    ViewBag.Title = "Create";
}

<h2>Loo uus osakond</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="font-size:20px">
        @Html.LabelFor(model => model.DepartmentName, "Osakond", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
        </div>
    </div>


    @*<div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Osakond", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentId", null, "-- vali osakond --", htmlAttributes: new { style = "background-color:lightgoldenrodyellow", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>*@


    @*<div class="form-group">
        @Html.LabelFor(model => model.Picture, "Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Picture", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })*@
</div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvesta" class="btn btn-primary" />
            </div>
        </div>
    
}

<div>
    <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class="btn btn-primary"})</b>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCuus/Views/Departments/Delete.cshtml
@model MVCuus.Models.Department

@{
    ViewBag.Title = "Delete";
}

<h2>Kustutamine</h2>

<h3>Kas oled kindel, et soovid kustutada osakonna?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal" style="font-size:20px">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @*<div class="form-actions no-color">*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kustuta" class="btn btn-primary" />
        </div>
    </div>
            <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class = "btn btn-primary" })</b>
            }
        </div>

MVCuus/Views/Departments/Details.cshtml
@model MVCuus.Models.Department

@{
    ViewBag.Title = "Details";
}

<h2>Detailid</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal" style="font-size:20px">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <b>@Html.ActionLink("Muuda", "Edit", null, routeValues:new { id = Model.Id} , htmlAttributes: new { @class = "btn btn-primary" })</b>
        </div>
    </div>
    <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class = "btn btn-primary" })</b>
</p>

MVCuus/Views/Departments/Edit.cshtml
@model MVCuus.Models.Department

@{
    ViewBag.Title = "Edit";
}
<h2>Muuda osakonda</h2>

@using (Html.BeginForm("Edit", "Departments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group" style="font-size:20px">
        @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.Picture, "Picture", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Picture", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>*@


    @*<div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Osakond", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentId", null, "-- vali osakond --", htmlAttributes: new { style = "background-color:lightgoldenrodyellow", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>*@


    @if (Model.Picture != null)
    {
        <img src="@Url.Action("Get", "Files", new { id = Model.Picture } )" height="120" />
        <br />
    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <label for="file">Pilt osakonnale:</label>
            <input type="file" name="file" id="file" @*class="btn btn-primary"*@ />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta" class="btn btn-primary" />
        </div>
    </div>
</div>
}
<div>
    <b>@Html.ActionLink("Tagasi listi", "Index", null, new { @class="btn btn-primary"})</b>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCuus/Views/Departments/Index.cshtml
@model IEnumerable<MVCuus.Models.Department>

@{
    ViewBag.Title = "Departments - Osakonnad";
}

<h2>Osakonnad</h2>

<p>
    @Html.ActionLink("Loo uus", "Create", null, new { @class = "btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.File.Filename)
        </th>
        <th></th>
    </tr>

   

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.File.Filename)
            </td>
            <td>
                @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>